from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from .error_pattern_library import ErrorPattern, find_matches, best_match

logger = logging.getLogger("diagnosis_engine")

if not logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(
        logging.Formatter("%(asctime)s | %(levelname)-8s | diagnosis_engine | %(message)s")
    )
    logger.addHandler(_handler)
    logger.setLevel(logging.INFO)


RiskLevel = str  # "low" | "medium" | "high" | "critical"


@dataclass
class FailureContext:
    """Everything known about a failed command, supplied by the caller."""

    command: str
    stdout: str
    stderr: str
    exit_code: int
    current_step: str = ""
    os_version: str = ""
    python_version: str = ""
    project_metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def combined_text(self) -> str:
        """Combine all text for pattern matching."""
        return f"{self.stdout}\n{self.stderr}\n{self.command}"


@dataclass
class Diagnosis:
    """
    Structured diagnosis result - DETERMINISTIC, NO AI.
    
    All values are derived from pattern matching, not generated by AI.
    """
    root_cause: str
    category: str
    possible_fixes: List[str]
    confidence: float
    risk_level: RiskLevel
    retry_recommended: bool
    estimated_success_probability: float
    matched_patterns: List[str]
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "root_cause": self.root_cause,
            "category": self.category,
            "possible_fixes": self.possible_fixes,
            "confidence": round(self.confidence, 3),
            "risk_level": self.risk_level,
            "retry_recommended": self.retry_recommended,
            "estimated_success_probability": round(self.estimated_success_probability, 3),
            "matched_patterns": self.matched_patterns[:5],
            "notes": self.notes,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)


# Risk categories - DETERMINISTIC, NO AI
_HIGH_RISK_CATEGORIES = {
    "disk_full",
    "no_space_left",
    "memory_exhaustion",
    "dependency_conflict",
    "service_failure",
}
_CRITICAL_RISK_CATEGORIES = {
    "permission_denied",
    "ssl_failure",
}


def _determine_risk_level(category: str, exit_code: int) -> RiskLevel:
    """Determine risk level based on category and exit code."""
    if category in _CRITICAL_RISK_CATEGORIES:
        return "critical"
    if category in _HIGH_RISK_CATEGORIES:
        return "high"
    if exit_code in (137, 139):  # SIGKILL / SIGSEGV
        return "high"
    return "low"


def _extract_placeholder_values(pattern: ErrorPattern, text: str) -> Dict[str, str]:
    """
    Extract regex capture groups (e.g. missing module name) for command templating.
    DETERMINISTIC - uses regex capture groups, no AI.
    """
    match = pattern.compiled().search(text)
    values: Dict[str, str] = {}
    
    if match and match.groups():
        # Map first capture group to {module}/{package} if available
        first_group = match.group(1)
        if first_group:
            values["module"] = first_group
            values["package"] = first_group
            # If there's a second group, map it too
            if len(match.groups()) >= 2:
                values["path"] = match.group(2)
                values["destination"] = match.group(2)
    
    return values


def _render_fix_commands(pattern: ErrorPattern, values: Dict[str, str]) -> List[str]:
    """Render fix commands with placeholder values."""
    rendered = []
    for cmd in pattern.fix_commands:
        try:
            rendered.append(cmd.format(**values))
        except (KeyError, IndexError):
            # If placeholder substitution fails, use the command as-is
            rendered.append(cmd)
    return rendered


def diagnose(context: FailureContext) -> Diagnosis:
    """
    Produce a structured diagnosis for a failed command.
    
    PURELY DETERMINISTIC - No AI, no LLM, no generation.
    Only uses pattern matching from error_pattern_library.py.
    """
    combined_text = context.combined_text
    matches = find_matches(combined_text)

    if not matches:
        logger.info(
            "No known error pattern matched for step '%s' (exit_code=%d).",
            context.current_step,
            context.exit_code,
        )
        return Diagnosis(
            root_cause="Unrecognized failure — no known pattern matched the output.",
            category="unknown",
            possible_fixes=[
                "Inspect the full stdout/stderr manually.",
                "Re-run the command with increased verbosity.",
                "Check upstream service status pages for outages.",
                "Add a new pattern to error_pattern_library.py.",
            ],
            confidence=0.15,
            risk_level="medium",
            retry_recommended=True,
            estimated_success_probability=0.25,
            matched_patterns=[],
            notes="Unknown error - consider adding a new pattern to the error_pattern_library.py"
        )

    # Use the highest confidence match
    top = matches[0]
    values = _extract_placeholder_values(top, combined_text)
    fixes = _render_fix_commands(top, values)

    # Blend confidence across all matches that share the same category
    # This prevents over-trusting a single fragile regex
    same_category_matches = [m for m in matches if m.category == top.category]
    aggregate_confidence = min(
        0.99, top.confidence + 0.03 * (len(same_category_matches) - 1)
    )

    risk = _determine_risk_level(top.category, context.exit_code)

    # Success probability heuristic:
    # - Start with confidence
    # - Discount by risk level
    # - Discount if fix is not safe to auto-execute
    risk_penalty = {
        "low": 0.0,
        "medium": 0.1,
        "high": 0.2,
        "critical": 0.35
    }.get(risk, 0.1)
    
    success_probability = max(
        0.05,
        aggregate_confidence * (0.9 if top.safe_to_auto_execute else 0.7) - risk_penalty,
    )

    diagnosis = Diagnosis(
        root_cause=top.description,
        category=top.category,
        possible_fixes=fixes,
        confidence=aggregate_confidence,
        risk_level=risk,
        retry_recommended=top.retry_original,
        estimated_success_probability=success_probability,
        matched_patterns=[p.pattern for p in matches[:5]],
        notes=(
            f"Matched {len(matches)} known pattern(s) for step '{context.current_step}'. "
            f"Top match category: '{top.category}' (confidence: {top.confidence:.2f}). "
            f"Total patterns matched: {len(matches)}."
        ),
    )
    
    logger.info(
        "Diagnosis for step '%s': category=%s confidence=%.2f risk=%s fixes=%d",
        context.current_step,
        diagnosis.category,
        diagnosis.confidence,
        diagnosis.risk_level,
        len(diagnosis.possible_fixes)
    )
    return diagnosis


def diagnose_to_json(context: FailureContext) -> str:
    """Convenience wrapper returning the diagnosis as a JSON string directly."""
    return diagnose(context).to_json()


def get_best_fix(context: FailureContext) -> Optional[Dict[str, Any]]:
    """
    Get the best fix for a failure context.
    
    Returns:
        {
            "fix_commands": List[str],
            "category": str,
            "description": str,
            "confidence": float,
        }
    """
    diagnosis = diagnose(context)
    
    if diagnosis.category == "unknown" or not diagnosis.possible_fixes:
        return None
    
    return {
        "fix_commands": diagnosis.possible_fixes,
        "category": diagnosis.category,
        "description": diagnosis.root_cause,
        "confidence": diagnosis.confidence,
    }


def get_fix_commands(context: FailureContext) -> List[str]:
    """
    Get fix commands only, without full diagnosis.
    """
    diagnosis = diagnose(context)
    return diagnosis.possible_fixes


# ==================== BACKWARD COMPATIBILITY ====================
# Maintain backward compatibility with old module name
# This allows existing code to continue working

# Create a compat class that mirrors the old interface
class AI_Diagnosis_Compat:
    """Backward compatibility wrapper."""
    
    @staticmethod
    def diagnose(context: FailureContext) -> Diagnosis:
        """Compatibility method - redirects to diagnose function."""
        return diagnose(context)
    
    @staticmethod
    def diagnose_to_json(context: FailureContext) -> str:
        """Compatibility method - redirects to diagnose_to_json function."""
        return diagnose_to_json(context)


# For backward compatibility with imports
# from ai_diagnosis import diagnose will still work
diagnose_legacy = diagnose
diagnose_to_json_legacy = diagnose_to_json


if __name__ == "__main__":
    # Test the diagnosis engine
    from .logger_service import get_logger
    
    logger = get_logger("test")
    
    # Test with SSL error
    context = FailureContext(
        command="pip install -r requirements.txt",
        stdout="",
        stderr="SSL: CERTIFICATE_VERIFY_FAILED",
        exit_code=1,
        current_step="install_deps",
        os_version="Ubuntu 22.04",
        python_version="3.11.0"
    )
    
    diagnosis = diagnose(context)
    print("=== DIAGNOSIS (DETERMINISTIC - NO AI) ===")
    print(diagnosis.to_json())
    
    # Test with unknown error
    unknown_context = FailureContext(
        command="some_command",
        stdout="",
        stderr="Some weird error nobody has seen",
        exit_code=255,
        current_step="unknown_step"
    )
    
    unknown_diagnosis = diagnose(unknown_context)
    print("\n=== UNKNOWN ERROR DIAGNOSIS ===")
    print(unknown_diagnosis.to_json())
    
    # Test get_best_fix
    best_fix = get_best_fix(context)
    if best_fix:
        print("\n=== BEST FIX ===")
        print(f"Category: {best_fix['category']}")
        print(f"Description: {best_fix['description']}")
        print(f"Confidence: {best_fix['confidence']}")
        print(f"Commands: {best_fix['fix_commands']}")